### ISSUE TITLE
Specifying just --channel-with-children channels does not export anything

### ISSUE THREAD

**Issue by aaannz** [uyuni-project/inter-server-sync#43]
Command `inter-server-sync export --channel-with-children="sle-product-sles15-sp3-pool-x86_64,sle-product-sles15-sp4-pool-x86_64" --outputDir export` does not export anything.

It should export parent and child channels instead.

**Comment by rjmateus** [comment]
this was solved in here: https://github.com/uyuni-project/inter-server-sync/pull/39

**Comment by aaannz** [comment]
Ah, missed that. It didn't make it to the release, right? Closing the issue.

**Comment by rjmateus** [comment]
It should be in the latest release: https://github.com/uyuni-project/inter-server-sync/blob/main/inter-server-sync.changes#L4-L6

**Comment by aaannz** [comment]
Ah, only for 4.3. We may want to release this for 4.2 as well. I see only 0.1.0 version there ( https://scc.suse.com/packages/22508296?name=SUSE%20Manager%20Server&version=4.2&arch=x86_64&query=inter-server-sync&module= )

**Comment by rjmateus** [comment]
I have merged for 4.2 also. Maybe is not already yet released
https://github.com/SUSE/spacewalk/issues/17878
